### ISSUE TITLE
Put PI key into RC

### ISSUE THREAD

**Issue by CJ-Wright** [regro/regolith#102]
It would be nice to have some group level information in the RC.
The group name is already there, it woudl be good to also include the name/key of the PI.

**Comment by scopatz** [comment]
Ahh yeah, there should probably be a groups collection

**Comment by CJ-Wright** [comment]
Yes, although what would that look like. I guess it is just one big document?

**Comment by scopatz** [comment]
normally probably.  But you can imagine outside collaborators where you might want information for their groups as well

**Comment by CJ-Wright** [comment]
That is fair. That actually brings up a good point, how do we share stuff between different group dbs?
