### ISSUE TITLE
package metadata not found

### ISSUE THREAD

**Issue by stevenhua0320** [regro/regolith#1161]

**Comment by sbillinge** [comment]
Fixes this warning obtained on windows by Simon:
```
$ C:\Users\simon\dev\regolith\src\regolith\version.py:38: UserWarning: Package metadata not found.
  warn("Package metadata not found.")
```

**Comment by bobleesj** [comment]
Closed by recutting. No more warning provided.

**Comment by bobleesj** [comment]
@sbillinge could you please close this issue? No permission for me. 

Closed by https://github.com/regro/regolith/pull/1191
