### ISSUE TITLE
Relocate `tests` folder to top project level

### ISSUE THREAD

**Issue by bobleesj** [regro/regolith#1178]
### Problem

Currently, the tests are located under `src/regolith/tests`.

### Proposed solution

move `tests` at the top directly level, side by side with `src`

**Comment by bobleesj** [comment]
Reference: https://github.com/Billingegroup/bg-mpl-stylesheets/

**Comment by tinatn29** [comment]
I ran `mv src/regolith/tests/* ./tests` to move everything in `src/regolith/tests` folder into the top directory `./tests`. Everything got moved except the `__pycache__` folder. Can I delete the old folder `src/regolith/tests` (including pycache)?

**Comment by bobleesj** [comment]
could you see if you could use `git mv` instead? Yes, you could remove `src/regolirth/tests` and `__pycache__` isn't uploaded github so yes you could remove it.

**Comment by tinatn29** [comment]
another question related to PR #1188 since it came up when I want to commit the move -- I think we should just make `flake8` in `.pre-commit-config.yaml` exclude `test_helpers.py` to avoid breaking tests

**Comment by sbillinge** [comment]
> also might need it to ignore `test_commands.py` as well. When running `pytest` after the move, it automatically detects functions in `conftest.py` without explicit imports (so tests are passing), but flake8 doesn't know this and keeps giving errors that there are unknown/unimported functions

This may mean we don't have things configured right. I can take a quick look

**Comment by bobleesj** [comment]
Closed by https://github.com/regro/regolith/pull/1191
