### ISSUE TITLE
Wondering purpose of `github_deploy_key.enc`

### ISSUE THREAD

**Issue by bobleesj** [regro/regolith#1179]
@sbillinge Could you please shed some light on the usage of this key? 

https://github.com/regro/regolith/blob/main/github_deploy_key.enc

**Comment by sbillinge** [comment]
no idea.  I think it is left over from CJ days.  Or it may be even from Anthony Scopatz days.  We could try and delete it.  There is a small chance it will break some backward compatitibility thing of some old website or something, but I think practically, regolith is not being use for too much by Anthony any more so it is probably safe to remove it.  it is not great to have keys in repos anyway.

**Comment by bobleesj** [comment]
@sbillinge Okay! Thanks for the explanation.

**Comment by bobleesj** [comment]
Closed by https://github.com/regro/regolith/pull/1212
