### ISSUE TITLE
Double check GitHub CI .yml files - there are more than enough of as now

### ISSUE THREAD

**Issue by bobleesj** [regro/regolith#1180]
### Problem

<img width="496" alt="Screenshot 2024-11-06 at 4 11 56 PM" src="https://github.com/user-attachments/assets/10ec920d-dc88-481e-92e4-eaecbe42d501">

A bit too many.

### Proposed solution

Once pytest is configured, we can re-visit this and remove the ones no longer needed.

**Comment by sbillinge** [comment]
I think in this case it is a simple cookie-cut isn't it?  We are just testing the regolith code....so we can use our new ways of doing that?

**Comment by bobleesj** [comment]
yes, simple cookiecutting - should have just mentioned that in the proposed solution

**Comment by bobleesj** [comment]
Closed by https://github.com/regro/regolith/pull/1212
