### ISSUE TITLE
Cookiecut - Python 3.11, 3.12, 3.13 priority tasks and communication channel

### ISSUE THREAD

**Issue by bobleesj** [regro/regolith#1182]
(To be closed after we are done with cookiecuting)

- always make a PR into the `cookie` branch

**Comment by bobleesj** [comment]
### Priority

1. Local pytest 

- [ ]  https://github.com/regro/regolith/issues/1178
- [ ] https://github.com/regro/regolith/issues/1177
- [ ] https://github.com/regro/regolith/issues/1053

2. Proper GitHub CI setup 
- [ ] https://github.com/regro/regolith/issues/1173
- [ ] https://github.com/regro/regolith/issues/1180

3. Cosmetics
- [ ] https://github.com/regro/regolith/issues/1170
- [ ] https://github.com/regro/regolith/issues/1053
- [ ] https://github.com/regro/regolith/issues/1179

@tinatn29 since I've created lots of issues, I wanted to organize them a bit  - we can use this issue here to communicate any tasks that are of interest to all maintainers/reviewers.

**Comment by bobleesj** [comment]
(A quick note to maintainers) recut this package before we are about to make a release checklist

**Comment by bobleesj** [comment]
@tinatn29 Since we have Python 3.11 CI configured here https://github.com/regro/regolith/pull/1203, we could address all of the issues under `Python 3.11 support (remove warnings/skipped tests)` above and then update our CI to 3.12, then 3.13, resolving issues systematically..

**Comment by bobleesj** [comment]
@sbillinge We still need to move test files outside of `src`. This, I will look into it. Then, we can probably merge `cookie` to `main`.

**Comment by bobleesj** [comment]
@sbillinge I double checked - `tests` is moved out of `src` already. Thanks to @tinatn29 

Yes, looks good to merge to `main`.

**Comment by bobleesj** [comment]
One last thing - @sbillinge  could you setup `pre-commit` at the repository level? It should all pass. 

<img width="689" alt="Screenshot 2024-12-11 at 8 59 43 PM" src="https://github.com/user-attachments/assets/cf58c01b-50ca-4bca-8d16-dd1fdcb27517" />

**Comment by sbillinge** [comment]
haha, getting to green...
![image](https://github.com/user-attachments/assets/a658486c-3e50-4729-ba32-f4901b33cea1)

pre-commit working on the repo....codecov working on the repo (everything red before).  The tests on pr (push) would turn red if I raran it as it runs the same thing as tests on pr (pull request).  I guess there is no news, but I think there may be a news that was merged direclty to main before we went to the cookie branch.  I will merge like this since tests are passing and then check.

**Comment by bobleesj** [comment]
@sbillinge @tinatn29  yes, great and steady progress.. it will be SO much easier to build on this repo moving forward!

**Comment by tinatn29** [comment]
@sbillinge @bobleesj How do I fix skipped tests #1200? Do I need to do this before proceeding with the API documentation step (is there an issue for this already?) and adding news #1214?

**Comment by sbillinge** [comment]
@bobleesj @tinatn29 I consider Regolith to be cookiecut so I am closing this issue.   The stlil open issues from this process I will move to the `0.10.0rc` release milestone on a separate issue.

**Comment by bobleesj** [comment]
Yes cookiecut is done
