### ISSUE TITLE
Fix pytest 40 warnings from matplotlib plot_date

### ISSUE THREAD

**Issue by tinatn29** [regro/regolith#1201]
### Problem
When running `pytest` on a Python 3.11 environment, the tests are passing but with 57 warnings (and skips). 40/57 warnings are matplotlib deprecation warnings for `plot_date`

### Proposed solution
Replace `plot_date` with `plot`

**Comment by bobleesj** [comment]
@tinatn29 I think you've fixed this issue. Let's close this!
