### ISSUE TITLE
subprocess problem not solved on windows :(

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#193]
@CJ-Wright 
```
________________________________ test_validate ________________________________

make_db = 'C:\\Users\\simon\\AppData\\Local\\Temp\\regolith_fake'

    def test_validate(make_db):
        repo = make_db
        os.chdir(repo)
        out = subprocess.run(["regolith", "validate"], check=False).out
>       assert "NO ERRORS IN DBS" in out
E       AssertionError: assert 'NO ERRORS IN DBS' in ''

..\..\..\..\dev\regolith\tests\test_validate.py:53: AssertionError
---------------------------- Captured stderr call -----------------------------
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
xonsh: subprocess mode: command not found: regolith
```

Actually, it looks as if it found subprocess.....so that is progress?

**Comment by CJ-Wright** [comment]
Hmm ok. It looks like regolith is not on your system path at that point.
Could it be possible you don't have xonsh installed in your environment? If that is the case can you install xonsh from conda-forge in the environment and try again? (If this used xonsh from somewhere else then that xonsh would not have access to regolith.)

Would it be possible to print out your system path somewhere in the failing test?

**Comment by sbillinge** [comment]
fyi, I did install xonsh into the environment.

I ran the test with a sys.path print statement and got this:
~\AppData\Local\Temp\regolith_fake ~\AppData\Local\Temp\regolith_fake
~\AppData\Local\Temp\regolith_fake ~\AppData\Local\Temp\regolith_fake
~\AppData\Local\Temp\regolith_fake ~\AppData\Local\Temp\regolith_fake
~\dev\regolith

~/dev/regolith  is the right place

**Comment by CJ-Wright** [comment]
@scopatz I'm currently stumped, what do you think?
