### ISSUE TITLE
people organization and institution management

### ISSUE THREAD

**Issue by CJ-Wright** [regro/regolith#202]
We now have two keys for employers, organization and institution. We need to get these two to work together at some point so that we properly load the name from institution (from the institution collection) if it exists.

**Comment by sbillinge** [comment]
yes. ;)

When I created ``institutions``, I wondered for a second whether it should be ``organizations``, which basically look like ``institutions`` but don't have ``schools`` and ``departments`` but different ``divisions`` and ``units`` and ``subunits``.   Ugh, why is the world so complicated.

Not sure what to say.  Ideas?

**Comment by sbillinge** [comment]
closed by #893
