### ISSUE TITLE
builders can take some command line switches?

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#249]
I often need to build things that are limited to certain date ranges, and filtered by person or grant, but it is a big lift to make a new builder each time.  Could we have optional command line arguments ``--from`` ``--to``?

It may make sense to allow switches for ``--bygrant`` or ``--byperson``, so  the build is broken out by grant, etc.

**Comment by scopatz** [comment]
I belive that this is possible by modifying the rc, as you figured out

**Comment by CJ-Wright** [comment]
To capture some notes from a discussion the other day, it might be good to extend this to accept arbitrary kwargs and use those for filtering where the pattern would be `--name_of_field=['acceptable', 'values']`. This doesn't work for time based filtering but I think that can be special cased.
