### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by CJ-Wright** [regro/regolith#38]
Have an import for running interactively in ipython

**Comment by scopatz** [comment]
What do you mean exactly?

**Comment by scopatz** [comment]
For which purpose? Input?

**Comment by CJ-Wright** [comment]
DB searching, since we don't have a db search frontend.
Eg
```python
from regolith.interactive import *
cj = [d for d in db['people'] if d['_id'] == CJ-Wright]
```

**Comment by CJ-Wright** [comment]
Input could also be nice (although flask seems to handle that reasonably ok)

**Comment by scopatz** [comment]
Oh I see, yeah that would be nice.
