### ISSUE TITLE
BUG: cannot trigger help message in l_projecta

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#434]
**desired behavior:** 
have a way to return the list of allowed flags and the usage

**current behavior:**
if unknown flags are given it just lists all projecta and not a usage message

There is a workaround that shomik used in the l_contact helper and we could reuse that here (require a fake ``run`` command).  If you can think of a better way that would be better though.

**Comment by mwinitch** [comment]
I will take care of this.
