### ISSUE TITLE
helper: general lister

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#452]
UC1:
1. simon types ``regolith helper list people``
1. lister lists the ids of all the people in people

UC2:
1. S types ``rh list people --kv_filter name simon``
1. l lists the id of all people in people who's name contains simon

UC3:
1. S types ``rh list people --kv_filter name simon -r name position``
1. l lists the id, name and position of all people in people who's name contains simon

UC4:
1. S types ``rh list people -k``
1. l returns a list of the available keys and their description (if available) in collection people

**Comment by dy2403** [comment]
I will take this!
