### ISSUE TITLE
ENH: projecta lister better handling of whether pra are open or closed

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#480]
current behavior:
Not sure, so documentation that is displayed by argparse help needs to be a bit richer, but I think by default it only lists pra that are open (not finished, cancelled or back_burner for example)

desired behavior:
other than a fix to the documentation to make this explicit, if the behavior is to list only open (not closed) pra by default, then a command line arg that allows this to be turned off (so ``--all`` prints all pra).  If, by default, it is printing all pra, then change default to just returning open pra.

**Comment by jiaweizang** [comment]
I will take this with issue 481 and 482.

**Comment by jiaweizang** [comment]
@mwinitch Another one!
