### ISSUE TITLE
ENH: notes for improving u_contact

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#524]
I did some testing and here are my thoughts to make this better:

1. On making the index list, change the help message to: "Please rerun the helper by hitting up arrow and adding  '-i list-index' to update the list item 'list-index', e.g., 'regolith helper eins -i 2'.  For new contacts --name (-n) and --institution (-o) are required:"  (let's make -i be the index in all the helpers.  Also, now the behavior is that the positional argument just looks for a person, but does not have double use as being the name when it is a new contact.)
1. In the list have the helper print the whole entry for the person.  This is important for an updater because how do I know what I want to update unless I can see what is there.   
1. Put the ID arg near the bottom when help is printed and in the help message say what it defaults to.  --database is always at the bottom, above it --date, then above that --aliases then above that --id (aliases and id don't need a short versions because we will rarely use them), then above that --notes (give -n for short), then above that --institution (-t) and above that --name (-n)
1. It is now time to fix the email.....this is one of the important things I want to update!  Place this below --institution and above notes in the help order.

**Comment by dy2403** [comment]
All but 4 were loved by `https://github.com/regro/regolith/pull/527`

**Comment by sbillinge** [comment]
please make a new issue for 4. and then we can close this issue.

**Comment by dy2403** [comment]
https://github.com/regro/regolith/issues/414
Done!
