### ISSUE TITLE
Add resume builder

### ISSUE THREAD

**Issue by scopatz** [regro/regolith#59]
This is distinct from a CV

**Comment by CJ-Wright** [comment]
Awesome. Is there anything specific that you want in the resume?

**Comment by scopatz** [comment]
basically, it should be a 2-page version of the CV without all the publications

**Comment by CJ-Wright** [comment]
I think this was closed by https://github.com/regro/regolith/commit/f3ad2637a42b29e68c45a920dccc8e024273a958
