### ISSUE TITLE
add ORCHID IDs to people

### ISSUE THREAD

**Issue by CJ-Wright** [regro/regolith#64]
Maybe have a dict of these kinds of external keys?

**Comment by scopatz** [comment]
Well, shouldn't this just be an optional key?

**Comment by scopatz** [comment]
It is a good suggestion, though!

**Comment by CJ-Wright** [comment]
that's fair. We may need a system for making keys required for an individual research group. I guess we can slam something into the RC

**Comment by scopatz** [comment]
yeah, that is an interesting idea, and probably the right place for it.

**Comment by CJ-Wright** [comment]
Eg, our group may require ORCHIDs since they are needed for JOSS.

**Comment by scopatz** [comment]
sure, makes sense to me
