### ISSUE TITLE
ENH: finish milestone

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#654]
add `--finish` to `u_milestone`.

this is the same as `u_milestone -s f` except that it adds today's date as "end_date" in the milestone and it takes a string argument that is put into a `report_summary` field

**Comment by connorjbracy** [comment]
@sbillinge, as per your message in Slack this is no longer an issue to be considered for the v0.6.0 release, correct?

**Comment by sbillinge** [comment]
Let me check it and get back to you
