### ISSUE TITLE
missing year when create new prum

### ISSUE THREAD

**Issue by dragonyanglong** [regro/regolith#662]
When use the a_projectum helper function, it doesn't include the year in the prum name anymore.

See `a_projectumhelper.py` file:
`key = f"{rc.lead[:2]}_{''.join(rc.name.casefold().split()).strip()}"`

**Comment by sbillinge** [comment]
this is desired behavior.  I realized that was needed when I was using the file-system for organizing things but not when using a db because I can write a lister that lists by date, for example.

**Comment by sbillinge** [comment]
@dragonyanglong thanks for catching that though!

**Comment by dragonyanglong** [comment]
opppps. sorry
