### ISSUE TITLE
Abstract lister helper Location vs Institution Filter

### ISSUE THREAD

**Issue by priyankaanehra** [regro/regolith#696]
The lister filters presentations via user entered arguments. There is an issue with the --loc_inst argument in particular. 

There are several presentations that are located at 'Columbia' for 'institution' but also for 'location'. The program currently would look through any seminars or colloquiums and if it finds matches, only output those types. However, this is problematic if you wanted the 'Columbia' matches that search in 'location' or if you wanted both that are in 'institution' and 'location'.

Potential Ideas from Simon:
-we can fix up the database
-we could put a couple of lines of code and throw an exception if the builder finds both in an entry or even better would be something in the database validation that checks for this.  Database validation is done using Cerberus.

**Comment by connorjbracy** [comment]
@pliu2781's PR to close this issue has seemingly passed CI and been verified. Consider closing this issue.

**Comment by sbillinge** [comment]
haha, I guess that this tested that pattern "closes issue#696" and it doesn't work.....  NP.,I will close.  The fix was in #796
