### ISSUE TITLE
utf-8 vs windows 1252

### ISSUE THREAD

**Issue by CJ-Wright** [regro/regolith#71]
It seems that on windows YAML tries to load the yaml files with cp1252 encoding, which causes breakage

**Comment by scopatz** [comment]
Yeah that is the default encoding on Windows. We can manually read in in a specific encoding (I think).

**Comment by CJ-Wright** [comment]
I think we can do `with open(encoding='utf8')`

**Comment by scopatz** [comment]
Yeppers
