### ISSUE TITLE
ENH: Add "version" flag to regolith

### ISSUE THREAD

**Issue by connorjbracy** [regro/regolith#819]
Currently, `regolith --version` only produces an error stating `"AttributeError: RunControl object has no attribute 'databases'."`. Whether there is or is not currently an alternative way of checking regolith's version from the CLI, we might want to setup `regolith --version` as it is a pretty standard way to do so that many users might expect to work.

**Comment by sbillinge** [comment]
I agree on this. I wanted to use this in the docs and it didn't work....

**Comment by sbillinge** [comment]
assigned to Fengkai

**Comment by sbillinge** [comment]
closed by #876
