### ISSUE TITLE
Command-line switches use dashes instead of underscores between words

### ISSUE THREAD

**Issue by N-G-Asker** [regro/regolith#942]
Copying and pasting request from @sbillinge here for tracking:
> It is convention that command line switches are written with dashes (which resolve to underscores in the variable). For consistency please can you make that change for everything. example --no_cal -> --no-cal. No other code needs to be edited in this case because --no-cal results in rc.no_cal == True internally.

**Comment by N-G-Asker** [comment]
I will be working this issue.

Would I be correct saying that you would like this changed for all helpers in Regolith, not just in the `a_presentations` adder? Not a heavy lift at all in either case -- just want to confirm before making the edits!

**Comment by sbillinge** [comment]
yes, that would be cool.  It should not be a heavy lift.
