### ISSUE TITLE
Have milestone lister show the milestone uuid

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#985]
Have the lister list the milestone uuid. 

In non-verbose mode have it look like:
```
2022-01-06 (aedes1) lead: dpeters, dp_take_projecta_to_mongo_in_production, create the rg-db-group equivalent db on the mongo atlas 
```
where `aedes1` are the first 6 symbols of the milestone uuid.

In verbose mode have it look like:
```
2022-01-06 (aedes1): lead: dpeters, dp_take_projecta_to_mongo_in_production, status: started
    Type: other
    Title: create the rg-db-group equivalent db on the mongo atlas cluster
    log url: 
    Purpose: create the official mongo backend db for the projecta collection
    Audience: dpeters, sbillinge, nasker
    Notes:
      - () (Simon) create a db on the billinge group atlas cluster that will contain the projecta collection
      - () (Simon) assign read and write privileges on new db to dpeters
      - () upload the entire projecta.yml file to the new atlas db using fs-to-mongo rego command
     uuid: aedes1dsrtesgdw4cdatesd
```
where `aedes1dsrtesgdw4cdatesd` would be the full uuid, whatever it is.

**Comment by sbillinge** [comment]
@dpeters001 can you take this one.  Please wait until I let you know.  I am adding the milestone ids to the schema and you will need them.

**Comment by dpeters001** [comment]
Got it.

**Comment by sbillinge** [comment]
OK @dpeters001 I merged the new schema etc. so milestones have uuids.  You  should be able to work on this now.  Make a PR and make the changes to the tests (what is your desired output, make the tests reflect that, have the tests fail) and I will review that, then you can work to modify the code so the tests pass and we can merge that.  In the meantime, we can work on new issues and attach them to the milestone to get there in a stepwise fashion.
